### ISSUE TITLE
Carousel breaks when using Astro View Transitions

### ISSUE THREAD

**Issue by Motschen** [claudiabdm/astro-carousel#3]
Astro View Transitions help to make page switching feel a lot smoother.
Unfortunately, astro-carousel breaks when using this feature.

Opening a carousel by clicking on an image works great the first time, but as soon as you navigate to another page, the carousel will not be displayed anymore on click.
I fixed this issue in my own components by adding an astro:before-swap event.
You can find documentation on that [here](https://docs.astro.build/en/guides/view-transitions/#astrobefore-swap).

Thank you for your work on this project, the carousel looks amazing, especially when themed!

**Comment by claudiabdm** [comment]
Thank you for reporting this! I'll work on adding compability with Astro View Transitions.

**Comment by claudiabdm** [comment]
@Motschen I fixed it in https://github.com/claudiabdm/astro-carousel/pull/5. 

I needed more than `astro:before-swap` to make it work. I haven't used Astro View Transition API until now, so feel free to check the implementation and let me know what you think!

**Comment by Motschen** [comment]
Thank you for getting to work on this so fast!
Unfortunately, the carousel is still broken in my project even with #5 applied.
But now that the code is more organized, I managed to find a fix by myself, I'll have a PR ready soon :)

**Comment by Motschen** [comment]
See #6
